[config]

[templates.kitty]
input_path = '/home/ihzabaker/.config/matugen/templates/kitty-colors.conf'
output_path = '/home/ihzabaker/.config/kitty/colors-matugen.conf'
post_hook = 'pkill -SIGUSR1 kitty'

# [templates.alacritty]
# input_path = '/home/ihzabaker/.config/matugen/templates/alacritty.toml'
# output_path = '/home/ihzabaker/.config/alacritty/colors.toml'

# [templates.rofi]
# input_path = '/home/ihzabaker/.config/matugen/templates/rofi-colors.rasi'
# output_path = '/home/ihzabaker/.config/rofi/colors.rasi'

[templates.btop]
input_path = '/home/ihzabaker/.config/matugen/templates/btop.theme'
output_path = '/home/ihzabaker/.config/btop/themes/matugen.theme'

# [templates.dunst]
# input_path = '/home/ihzabaker/.config/matugen/templates/dunstrc-colors'
# output_path = '/home/ihzabaker/.config/dunst/dunstrc'

[templates.hyprland]
input_path = '/home/ihzabaker/.config/matugen/templates/hyprland-colors.conf'
output_path = '/home/ihzabaker/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '/home/ihzabaker/.config/matugen/templates/colors.css'
output_path = '/home/ihzabaker/.config/waybar/colors.css'
# post_hook = 'pkill -SIGUSR2 waybar'

# [templates.gtk3]
# input_path = '/home/ihzabaker/.config/matugen/templates/gtk-colors.css'
# output_path = '/home/ihzabaker/.config/gtk-3.0/gtk.css'
#
# [templates.gtk4]
# input_path = '/home/ihzabaker/.config/matugen/templates/gtk-colors.css'
# output_path = '/home/ihzabaker/.config/gtk-4.0/gtk-dark.css'

# [templates.sway]
# input_path = '/home/ihzabaker/.config/matugen/templates/sway-colors.conf'
# output_path = '/home/ihzabaker/.config/swayosd/colors.conf'

# [templates.nwgdock]
# input_path = '/home/ihzabaker/.config/matugen/templates/colors.css'
# output_path = '/home/ihzabaker/.config/nwg-dock-hyprland/colors.css'

